export const experience = {
  "02/24": {
    company: "Aura",
    website: "https://auranft.co/",
    from: "Feb 2024",
    to: "Current",
    designation: "Frontend Enginer",
    location: "Remote",
    tasks: "Build, style, create new features to provide users more customization and better usability. Optimize the performance of the application by leveraging Server Side rendering and partial rendering to provide the best user experience. Collaborate with designers and other engineers to build pixel perfect UI and come up with best possible solutions.",
    tech: ["Next.js", "React.js", "Web3.js", "Ethers.js", "SSR", "Typescript"],
  },
  "08/23": {
    company: "Mojoboxx",
    website: "https://mojoboxx.com/",
    from: "Aug 2023",
    to: "Feb 2024",
    designation: "Full Stack Developer",
    location: "Gurugram, India",
    tasks: "Crafted an online hotel booking platform from scratch in partnership with Cleartrip. Devised 20+ responsive, mobile first screens, significantly enhancing the UX. Integrated third-party APIs like Google Maps, Paytm, & Cleartrip. Collaborate with marketing team to bring new ideas to life. Optimize data fetching from third-party APIs to reduce load times.",
    tech: [
      "React.js",
      "Node.js",
      "Express.js",
      "Mysql",
      "HTML/CSS",
      "Javascript",
    ],
  },
  "07/2022": {
    company: "Amadeus",
    website: "https://amadeus.com/en",
    from: "July 2022",
    to: "May 2023",
    designation: "Software Engineer Graduate",
    location: "London, United Kingdom",
    tasks: "Develop crucial features for the various airlines. Collaborate with Product manager to refine the scope of current features, and build them. Provide selective features for airlines by utilizing feature flags. Work with designer to provide the best user experience to airport agents.",
    tech: ["Swift", "SwiftUI", "Objective-C", "UiKit"],
  },
  "06/2021": {
    company: "CSRN",
    website: "https://csrn.org.uk/",
    from: "June 2021",
    to: "August 2021",
    designation: "Software Engineer Intern",
    location: "London, United Kingdom",
    tasks: "Conceptualized a new project management platform which can be used by the organization for various upcoming projects.",
    tech: ["React.js", "MongoDb", "HTML/CSS", "Javascript"],
  },
};
